import fs from "fs";
import readline from "readline";
import chalk from "chalk";
import { getEnvPath, getHolocronDir, getStoragePath } from "../paths.js";
import { printSuccess } from "../docker.js";

function ask(question: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

const PROVIDERS = [
  { id: "k2think", label: "K2 Think (recommended for demos)", keyEnv: "K2THINK_API_KEY" },
  { id: "openai", label: "OpenAI", keyEnv: "OPENAI_API_KEY" },
  { id: "anthropic", label: "Anthropic", keyEnv: "ANTHROPIC_API_KEY" },
  { id: "google", label: "Google Gemini", keyEnv: "GOOGLE_API_KEY" },
  { id: "openrouter", label: "OpenRouter", keyEnv: "OPENROUTER_API_KEY" },
  { id: "custom", label: "Custom OpenAI-compatible", keyEnv: "LLM_API_KEY" },
] as const;

const DEFAULTS: Record<string, { base: string; model: string }> = {
  k2think: {
    base: "https://www.k2think.ai/api/chat/completions",
    model: "MBZUAI-IFM/K2-Think-v2",
  },
  openai: { base: "https://api.openai.com/v1", model: "gpt-4o" },
  anthropic: { base: "https://api.anthropic.com", model: "claude-sonnet-4-20250514" },
  google: {
    base: "https://generativelanguage.googleapis.com/v1beta/openai",
    model: "gemini-2.0-flash",
  },
  openrouter: { base: "https://openrouter.ai/api/v1", model: "openai/gpt-4o" },
  custom: { base: "http://localhost:11434/v1", model: "llama3.2" },
};

export async function setupCommand() {
  console.log(chalk.bold("\nHolocron Setup\n"));
  console.log(chalk.dim("Docker Desktop is the only required prerequisite.\n"));

  getHolocronDir();
  const envPath = getEnvPath();

  if (fs.existsSync(envPath)) {
    console.log("Existing config found at", envPath);
    const overwrite = await ask("Overwrite? (y/N): ");
    if (overwrite.toLowerCase() !== "y") {
      printSuccess("Setup skipped.");
      return;
    }
  }

  console.log(chalk.bold("LLM providers:"));
  PROVIDERS.forEach((p, i) => {
    console.log(`  ${i + 1}. ${p.label}`);
  });

  const choice = await ask("\nChoose provider [1]: ");
  const idx = choice ? Math.max(1, Math.min(PROVIDERS.length, parseInt(choice, 10) || 1)) - 1 : 0;
  const provider = PROVIDERS[idx];
  const defaults = DEFAULTS[provider.id];

  let apiKey = await ask(`${provider.label} API key (Enter for mock mode): `);
  if (!apiKey) {
    if (provider.id === "k2think") {
      console.log(chalk.yellow("Using mock mode. Request a key at https://build.k2think.ai/"));
    } else {
      console.log(chalk.yellow("Using mock mode — generations will return placeholder content."));
    }
    apiKey = "mock-key-for-dev";
  }

  let baseUrl = defaults.base;
  const customBase = await ask(`Base URL [${baseUrl}]: `);
  if (customBase) baseUrl = customBase;

  let model = defaults.model;
  const customModel = await ask(`Model [${model}]: `);
  if (customModel) model = customModel;

  const s2Key = await ask("Semantic Scholar API key (optional, Enter to skip): ");

  const storagePath = getStoragePath().replace(/\\/g, "/");

  const envLines = [
    `# Holocron config — generated by holocron setup`,
    `LLM_PROVIDER=${provider.id}`,
    `LLM_API_KEY=${apiKey}`,
    `LLM_BASE_URL=${baseUrl}`,
    `LLM_MODEL=${model}`,
    `K2THINK_API_KEY=${provider.id === "k2think" ? apiKey : "mock-key-for-dev"}`,
    `K2THINK_BASE_URL=${provider.id === "k2think" ? baseUrl : DEFAULTS.k2think.base}`,
    `K2THINK_MODEL=${provider.id === "k2think" ? model : DEFAULTS.k2think.model}`,
    `OPENAI_API_KEY=${provider.id === "openai" ? apiKey : ""}`,
    `ANTHROPIC_API_KEY=${provider.id === "anthropic" ? apiKey : ""}`,
    `GOOGLE_API_KEY=${provider.id === "google" ? apiKey : ""}`,
    `OPENROUTER_API_KEY=${provider.id === "openrouter" ? apiKey : ""}`,
    `SEMANTIC_SCHOLAR_API_KEY=${s2Key}`,
    `DATABASE_URL=postgresql://holocron:holocron@localhost:5432/holocron`,
    `STORAGE_PATH=${storagePath}`,
    `AUTH_MODE=local`,
    `AGENTS_SERVICE_URL=http://localhost:8000`,
    `NEXT_PUBLIC_AGENTS_URL=http://localhost:8000`,
    `SUPERMEMORY_API_URL=http://localhost:6767`,
    `SUPERMEMORY_API_KEY=`,
  ];

  fs.writeFileSync(envPath, envLines.join("\n") + "\n");
  printSuccess(`Config saved to ${envPath}`);
  console.log(chalk.dim("\nRun `holocron start` to launch Holocron.\n"));
}
