import fs from "fs";
import readline from "readline";
import chalk from "chalk";
import { getEnvPath, getHolocronDir, getStoragePath } from "../paths.js";
import { printSuccess } from "../docker.js";

function ask(question: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

export async function setupCommand() {
  console.log(chalk.bold("\nHolocron Setup\n"));

  getHolocronDir();
  const envPath = getEnvPath();

  let k2Key = "";
  let k2Base = "https://www.k2think.ai/api/chat/completions";
  let s2Key = "";

  if (fs.existsSync(envPath)) {
    const existing = fs.readFileSync(envPath, "utf-8");
    const keyMatch = existing.match(/K2THINK_API_KEY=(.+)/);
    if (keyMatch?.[1]) {
      console.log("Existing config found at", envPath);
      const overwrite = await ask("Overwrite? (y/N): ");
      if (overwrite.toLowerCase() !== "y") {
        printSuccess("Setup skipped.");
        return;
      }
    }
  }

  k2Key = await ask("K2 Think API key (required): ");
  if (!k2Key) {
    console.log(chalk.yellow("Request a key at https://build.k2think.ai/"));
    k2Key = "mock-key-for-dev";
  }

  const customBase = await ask(`K2 Think base URL [${k2Base}]: `);
  if (customBase) k2Base = customBase;

  s2Key = await ask("Semantic Scholar API key (optional, Enter to skip): ");

  const storagePath = getStoragePath().replace(/\\/g, "/");

  const envContent = `# Holocron config — generated by holocron setup
K2THINK_API_KEY=${k2Key}
K2THINK_BASE_URL=${k2Base}
K2THINK_MODEL=MBZUAI-IFM/K2-Think-v2
SEMANTIC_SCHOLAR_API_KEY=${s2Key}
DATABASE_URL=postgresql://holocron:holocron@localhost:5432/holocron
STORAGE_PATH=${storagePath}
AUTH_MODE=local
AGENTS_SERVICE_URL=http://localhost:8000
NEXT_PUBLIC_AGENTS_URL=http://localhost:8000
`;

  fs.writeFileSync(envPath, envContent);
  printSuccess(`Config saved to ${envPath}`);
  console.log(chalk.dim("\nRun `holocron start` to launch AcademicHub.\n"));
}
